document.addEventListener("DOMContentLoaded", function () {
  const grid = document.getElementById("interactive-grid");

  // List of pages (Replace with actual links)
  const pages = [
    { name: "2048 Game", url: "pages/2048 game.html" },
    { name: "ASCII Art", url: "pages/ascii-art.html" },
    { name: "Audio Visualization", url: "pages/audio-viz.html" },
    { name: "Aurora Flow", url: "pages/aurora-flow.html" },
    { name: "Block Breaker", url: "pages/block-breaker.html" },
    { name: "Bubble Pop", url: "pages/bubble-pop.html" },
    { name: "Chrono Ripples", url: "pages/chrono-ripples.html" },
    { name: "Circuit Life", url: "pages/circuit-life.html" },
    { name: "Clock Chaos", url: "pages/clock-chaos.html" },
    { name: "Color Pulse", url: "pages/color-pulse.html" },
    { name: "Colorclash", url: "pages/colorclash.html" },
    { name: "Cursor Eclipse", url: "pages/cursor-eclipse.html" },
    { name: "Cyber Flow", url: "pages/cyber-flow.html" },
    { name: "Digital Circuit", url: "pages/digital-circuit.html" },
    { name: "Digital Dreams", url: "pages/digital-dreams.html" },
    { name: "Digital Rain Piano", url: "pages/digital-rain-piano.html" },
    { name: "Digital Sand", url: "pages/digital-sand.html" },
    { name: "DNA Synthesizer", url: "pages/dna-synthesizer.html" },
    { name: "Dramatic Button", url: "pages/dramatic-button.html" },
    { name: "Dream Weaver", url: "pages/dream-weaver.html" },
    { name: "Ecosystem Builder", url: "pages/ecosystem-builder.html" },
    { name: "Elemental Playground", url: "pages/elemental-playground.html" },
    { name: "Error Dance Party", url: "pages/error-dance-party.html" },
    { name: "Gravity Particles", url: "pages/gravity-particles.html" },
    { name: "Impossible Button", url: "pages/impossible-button.html" },
    { name: "Light Bridge", url: "pages/light-bridge.html" },
    { name: "Matrix Rain", url: "pages/matrix-rain.html" },
    { name: "Memory Cards", url: "pages/memory-cards.html" },
    { name: "Memory Safari", url: "pages/memory-safari.html" },
    { name: "Nebula Flow", url: "pages/nebula-flow.html" },
    { name: "Neon Birds", url: "pages/neon-birds.html" },
    { name: "Neon Creator", url: "pages/neon-creator.html" },
    { name: "Neon DNA", url: "pages/neon-dna.html" },
    { name: "Neon Hexagons", url: "pages/neon-hexagons.html" },
    { name: "Neon Particles", url: "pages/neon-particles.html" },
    { name: "Neon Pong", url: "pages/neon-pong.html" },
    { name: "Neon Rain", url: "pages/neon-rain.html" },
    { name: "Neon Runner", url: "pages/neon-runner.html" },
    { name: "Neon Snake", url: "pages/neon-snake.html" },
    { name: "Neon Typewriter", url: "pages/neon-typewriter.html" },
    { name: "Neonpaint", url: "pages/neonpaint.html" },
    { name: "Neural Painter", url: "pages/neural-painter.html" },
    { name: "Particle Effects", url: "pages/particle-effects.html" },
    { name: "Particle Explosion", url: "pages/particle-explosion.html" },
    { name: "Pattern IQ", url: "pages/pattern-iq.html" },
    { name: "Pixel Garden", url: "pages/pixel-garden.html" },
    { name: "Pixel Pet", url: "pages/pixel-pet.html" },
    { name: "Pixel Rain", url: "pages/pixel-rain.html" },
    { name: "Quantum Bubble", url: "pages/quantum-bubble.html" },
    { name: "Quantum Flow", url: "pages/quantum-flow.html" },
    { name: "Reality Bender", url: "pages/reality-bender.html" },
    { name: "Scroll Metrics", url: "pages/scroll-metrics.html" },
    { name: "Sky Ace", url: "pages/sky-ace.html" },
    { name: "Sound Waves", url: "pages/sound-waves.html" },
    { name: "Space Tunnel", url: "pages/space-tunnel.html" },
    { name: "Spectrum", url: "pages/spectrum.html" },
    { name: "Tic-Tac-Toe Game", url: "pages/tic-tac-toe.html" },
    { name: "Time Paint", url: "pages/time-paint.html" },
    { name: "Time Weaver", url: "pages/time-weaver.html" },
    { name: "Void Screamer", url: "pages/void-screamer.html" },
    { name: "Wave Pool", url: "pages/wave-pool.html" },
    { name: "Wave Rider", url: "pages/wave-rider.html" },
    { name: "Word Blender", url: "pages/word-blender.html" }
  ];

  // Populate the grid with links
  pages.forEach(page => {
    let link = document.createElement("a");
    link.href = page.url;
    link.className = "grid-item";
    link.innerText = page.name;
    grid.appendChild(link);
  });
});

// Random page function
function randomPage() {
  const pages = [
    "pages/2048-game.html",
    "pages/ascii-art.html",
    "pages/audio-viz.html",
    "pages/aurora-flow.html",
    "pages/block-breaker.html",
    "pages/bubble-pop.html",
    "pages/chrono-ripples.html",
    "pages/circuit-life.html",
    "pages/clock-chaos.html",
    "pages/color-pulse.html",
    "pages/colorclash.html",
    "pages/cursor-eclipse.html",
    "pages/cyber-flow.html",
    "pages/digital-circuit.html",
    "pages/digital-dreams.html",
    "pages/digital-rain-piano.html",
    "pages/digital-sand.html",
    "pages/dna-synthesizer.html",
    "pages/dramatic-button.html",
    "pages/dream-weaver.html",
    "pages/ecosystem-builder.html",
    "pages/elemental-playground.html",
    "pages/error-dance-party.html",
    "pages/gravity-particles.html",
    "pages/impossible-button.html",
    "pages/light-bridge.html",
    "pages/matrix-rain.html",
    "pages/memory-cards.html",
    "pages/memory-safari.html",
    "pages/nebula-flow.html",
    "pages/neon-birds.html",
    "pages/neon-creator.html",
    "pages/neon-dna.html",
    "pages/neon-hexagons.html",
    "pages/neon-particles.html",
    "pages/neon-pong.html",
    "pages/neon-rain.html",
    "pages/neon-runner.html",
    "pages/neon-snake.html",
    "pages/neon-typewriter.html",
    "pages/neonpaint.html",
    "pages/neural-painter.html",
    "pages/particle-effects.html",
    "pages/particle-explosion.html",
    "pages/pattern-iq.html",
    "pages/pixel-garden.html",
    "pages/pixel-pet.html",
    "pages/pixel-rain.html",
    "pages/quantum-bubble.html",
    "pages/quantum-flow.html",
    "pages/reality-bender.html",
    "pages/scroll-metrics.html",
    "pages/sky-ace.html",
    "pages/sound-waves.html",
    "pages/space-tunnel.html",
    "pages/spectrum.html",
    "pages/tic-tac-toe.html",
    "pages/time-paint.html",
    "pages/time-weaver.html",
    "pages/void-screamer.html",
    "pages/wave-pool.html",
    "pages/wave-rider.html",
    "pages/word-blender.html"
  ];
  const randomIndex = Math.floor(Math.random() * pages.length);
  window.location.href = pages[randomIndex];
}